### ISSUE TITLE
channel：wecaht_mp，运行启动成功，显示监听http://0.0.0.0:8088/

### ISSUE THREAD

**Issue by 6vision** [zhayujie/bot-on-anything#147]
[INFO][2023-03-16 19:46:26][log.py:34] - [INIT] Start up: chatgpt on wechat_mp
[INFO][2023-03-16 19:46:26][wechat_mp_channel.py:44] - [WX_Public] Wechat Public account service start!
Bottle v0.12.25 server starting up (using AutoServer())...
Listening on http://0.0.0.0:8088/
Hit Ctrl-C to quit.

这是什么原因呢

**Comment by baichisong** [comment]
就是监听这个端口ya

> [INFO][2023-03-16 19:46:26][log.py:34] - [INIT] Start up: chatgpt on wechat_mp [INFO][2023-03-16 19:46:26][wechat_mp_channel.py:44] - [WX_Public] Wechat Public account service start! Bottle v0.12.25 server starting up (using AutoServer())... Listening on http://0.0.0.0:8088/ Hit Ctrl-C to quit.
> 
> 这是什么原因呢

就是这样的，监听8088端口，估计你在配置里port号定义了8088，最好定义80吧，因为公众号只能指向80。

**Comment by 6vision** [comment]
> 就是监听这个端口ya
> 
> > [INFO][2023-03-16 19:46:26][log.py:34] - [INIT] Start up: chatgpt on wechat_mp [INFO][2023-03-16 19:46:26][wechat_mp_channel.py:44] - [WX_Public] Wechat Public account service start! Bottle v0.12.25 server starting up (using AutoServer())... Listening on http://0.0.0.0:8088/ Hit Ctrl-C to quit.
> > 这是什么原因呢
> 
> 就是这样的，监听8088端口，估计你在配置里port号定义了8088，最好定义80吧，因为公众号只能指向80。

确实，是我80端口占用，显示0.0.0.0:8088没毛病，用一个没占用80端口的测试成功

**Comment by 6vision** [comment]
> 0.0.0.0也是一样的，跟127.0.0.1都代表本地localhost
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年03月16日 22:43 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [zhayujie/bot-on-anything] channel：wecaht_mp，运行启动成功，显示监听http://0.0.0.0:8088/ (Issue #147) | 就是监听这个端口ya [INFO][2023-03-16 19:46:26][log.py:34] - [INIT] Start up: chatgpt on wechat_mp [INFO][2023-03-16 19:46:26][wechat_mp_channel.py:44] - [WX_Public] Wechat Public account service start! Bottle v0.12.25 server starting up (using AutoServer())... Listening on http://0.0.0.0:8088/ Hit Ctrl-C to quit. 这是什么原因呢 就是这样的，监听8088端口，估计你在配置里port号定义了8088，最好定义80吧，因为公众号只能指向80。 监听地址不应该是127.0.0.1:8088么?我这显示0.0.0.0：8088，也可以么 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

谢谢解答，学到了，你会配置反向代理么，我博客占用了80端口

**Comment by baichisong** [comment]
你安装个nginx，然后用80接口接受，然后转发到8088



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月17日 07:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zhayujie/bot-on-anything] channel：wecaht_mp，运行启动成功，显示监听http://0.0.0.0:8088/ (Issue #147) |

0.0.0.0也是一样的，跟127.0.0.1都代表本地localhost
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年03月16日 22:43 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [zhayujie/bot-on-anything] channel：wecaht_mp，运行启动成功，显示监听http://0.0.0.0:8088/ (Issue #147) | 就是监听这个端口ya [INFO][2023-03-16 19:46:26][log.py:34] - [INIT] Start up: chatgpt on wechat_mp [INFO][2023-03-16 19:46:26][wechat_mp_channel.py:44] - [WX_Public] Wechat Public account service start! Bottle v0.12.25 server starting up (using AutoServer())... Listening on http://0.0.0.0:8088/ Hit Ctrl-C to quit. 这是什么原因呢 就是这样的，监听8088端口，估计你在配置里port号定义了8088，最好定义80吧，因为公众号只能指向80。 监听地址不应该是127.0.0.1:8088么?我这显示0.0.0.0：8088，也可以么 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***>

谢谢解答，学到了，你会配置反向代理么，我博客占用了80端口

**Comment by Martin-dq** [comment]
我也遇到了80端口被v2占用了，ngxin也不能动，难道要再搞个apache？
